version: '3.8'

services:
  king-10:
    image: david-10
    build: .
    ports:
      - '6004:3009'
    environment:
      - MONGODB-URI:'mongodb://mongodb-container:27017/LoanApplication'
    depends_on:
      - mongodb

  mongodb:
    image: mango:latest
    ports:
      - '27017:27017'
